#ifndef META_DATA_H
#define META_DATA_H

typedef enum {
    META_TYPE_PURE = 0,
    META_TYPE_DYNAMIC_DEPENDENT = 1,
    META_TYPE_OUTPUTED = 2,
    META_TYPE_WITH_SIDE_EFFECT = 4,
    META_TYPE_IMPURE = META_TYPE_OUTPUTED | META_TYPE_DYNAMIC_DEPENDENT | META_TYPE_WITH_SIDE_EFFECT
} MetaType;

#endif // META_DATA_H
